baseURL = 'https://63n0.github.io/'
languageCode = 'ja-jp'
title = '63n0 のブログ'
# theme = 'ananke'
theme = 'm10c'
favicon = "/favicon.ico"


[params]
	author = "63n0"
	description = "セキュリティ初心者の学生。WiFi周りに若干詳しいつもり。"
	avatar = "/avatar.png"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.goldmark]
	[markup.goldmark.extensions]
	  definitionList = true
	  footnote = true
	  strikethrough=true
	  table = true
	  taskList = true
	[markup.goldmark.extensions.cjk]
	  eastAsianLineBreaks = true
	  eastAsianLineBreaksStyle = 'simple'

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
